package io.werk24.model;

public enum W24TechreadExceptionType {
    DRAWING_FILE_FORMAT_UNSUPPORTED,
    DRAWING_FILE_SIZE_TOO_LARGE,
    DRAWING_RESOLUTION_TOO_LOW,
    DRAWING_NOISE_TOO_HIGH,
    DRAWING_CONTENT_NOT_UNDERSTOOD,
    DRAWING_PAPER_SIZE_TOO_LARGE,
    DRAWING_MEASURE_SYSTEM_INCOMPLETE,
    MODEL_FILE_FORMAT_UNSUPPORTED,
    MODEL_FILE_SIZE_TOO_LARGE,
    SUB_ACCOUNT_ACCESS_DENIED,
    SUB_ACCOUNT_NO_BALANCE
}
