package io.werk24.model;
import java.util.Map;

import lombok.Data;

@Data
public class W24TechreadMessage extends W24TechreadBaseResponse {
    /**
     *  Message format for messages that are sent
     * from the server to the client.
     */

    /**
     * UUID4 identifier that is generated by the server to identify
     * the request. This request_id can also be used to generate
     * helpdesk tickets for problems with this file.
     */
    private String request_id;

    /**
     * Main Message Type (see W24TechreadMessageType)
     */
    private W24TechreadMessageType message_type;

    /**
     * Message SubType (see W24TechreadMessageSubtype)
     */
    private String message_subtype;

    /**
     * Page number that the response belongs to.
     * Starts at zero. Yes, we were born in the 1900s.
     */
    private int page_number =  0;

    /**
     * Payload dictionary containing the response
     * as dict. The MessageType/Subtype will tell the
     * interpreter how to turn the payload back into
     * the corresponding object
     */
    private Map payload_dict = null;

    /**
     * For binary data, the API will return a download
     * url which carries the data. This allows us to transfer
     * larger images etc.
     */
    private String payload_url = null;

    /**
     * Binary reference of the payload. This will only
     * become available after the client has downloaded the
     * payload_url.
     */
    private String payload_bytes = null;

}

